spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newdb
    username: carami
    password: kang1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
